// sounds.h
#ifndef SOUNDS_H
#define SOUNDS_H

enum SOUNDTYPE {
    SOUND_MOVE,
    SOUND_CHECK,
    SOUND_CHECKMATE,
    SOUND_CAPTURE,
    SOUND_PROMOTION,
    SOUND_CASTLING,
    SOUND_ENPASSANT,
    SOUND_GAME_OVER,
    SOUND_START,
    SOUND_COUNT,
    CHAT_RECEIVED,
    RGAME_STARTED,
    CHAT_SEND
};


#endif // SOUNDS_H
